spring:
  main:
    # this solution for reference problem is described here https://github.com/spring-cloud/spring-cloud-dataflow/commit/2eeba7a8fb466e580c596aa959ed9f9392979cbe
    # the solution ticket is still open at https://github.com/spring-cloud/spring-cloud-dataflow/issues/4795
    allow-circular-references: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tank-of-america
    username: root
    password: tdd-cd
  jpa:
      show-sql: false